### ISSUE TITLE
Generating a single-page HTML?

### ISSUE THREAD

**Issue by zopyx** [oxygenxml/dita-css#6]
I know that dita-css creates somewhere and somehow a single-page HTML as input for an external
CSS Paged Media converter. Is it possible to get hold of this file as part of the conversion process?

**Comment by raducoravu** [comment]
Actually this transform reused most of the standard PDF transform which creates a single merged DITA Map in which topic references have been replaced by the topic content. So the CSSs style directly the DITA content and not XHTML output received from DITA content.
Indeed it is possible to construct a plugin to style XHTML content and obtain PDF from that.
